language: python
os: linux
dist: bionic

jobs:
  include:
    - python: 3.5
      env: PYVERSION=35
    - python: 3.6
      env: PYVERSION=36
    - python: 3.7
      env: PYVERSION=37
    - python: 3.8
      env: PYVERSION=38

install:
  - pip install --upgrade pip # might help fix pyqt5 issue
  - pip install -q pytest pytest-runner pytest-cov coverage
  - pip install coveralls
  - pip install -e .

script:
  - xvfb-run python setup.py test

after_success:
  - "ls -lr htmlcov"
  - coveralls
